name: Deploy Staging

on:
  push:
    branches:
      - "staging"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Running the build script
        run: npm run build-staging # Running script from package.json

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CF_PAGES_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: "finsquid-auth-sdk-staging"
          directory: "./dist"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
